editing of task 1 of module 4 of the course book
js-tasks-ru/js-20220729_kirill2231 pull request #8
Opened 2022-08-13 07:59 UTC by KirillKoch

Сделал правки компонента ColumnChart

2022-08-13 08:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-13 11:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-14 19:25 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  constructor(
good 👍

2022-08-14 19:25 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  getCachingElements() {
good 👍

2022-08-16 12:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-16 12:33 UTC, KirillKoch commented
Задачи из 5 модуля:
1) В 1 задаче не проходит 1 тест (should have ability to define target element for rendering). Не понял, что этот тест делает.
2) Не знаю, как связать функцию сортировки sortStrings, которая принимает массив строк, c dom-элементами .sortable-table__row?

2022-08-16 14:32 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    const notificationElements = document.querySelectorAll('[data-element="notification"]');
так делать нельзя! не следует обращаться к `DOM` чтобы спрятать предыдущий нотификейшен

2022-08-16 14:33 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show() {
`show` метод должен уметь принять в качестве аргумента ссылку на `DOM` элемент, в который мы отобразим нотификейшен,  либо если значение не передано - отобразим нотификейшен в `document.body`

2022-08-16 14:34 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +      return template + config.map(configElem => {
здесь лучше использовать строковую интерполяцию:
```
return `<a href="#" class="sortable-table__row">
  ${config.map...}
</a>
```

2022-08-16 14:36 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    const arr = this.element.querySelectorAll('.sortable-table__row');
так делать нельзя!
У нас данные хранятся в `this.data`. Мы должны отсортировать `this.data` и на основе отсортированных данных выполнить метод `addCellTableBody` и обновить таблицу

2022-08-16 14:36 UTC, dosandk requested changes
см. комменты

2022-08-17 14:10 UTC, closed without merging